apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: app
spec:
  containers:
  - name: liveness
    image: <your-registry>/app
    livenessProbe:
      httpGet:
        path: /healthz
        port: 5000
      initialDelaySeconds: 3
      periodSeconds: 3
